{% set python_min = '3.11' %}
{%- set name = "bobleesj.utils" -%}
{%- set version = "0.0.5" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bobleesj_utils/bobleesj_utils-{{ version }}.tar.gz
  sha256: 4345370dfb5e5c52c26e56bfb28c30a04117050f8faf311a2aab13865ef80c29

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - openpyxl

test: 
  requires:
    - pip
    - pytest
    - DeepDiff
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/bobleesj/bobleesj.utils/
  summary: Shared utilities for bobleesj packages.
  license: BSD-3-Clause
  license_file: LICENSE.rst
  description: |
    Python package for sharing utility functions and classes in materials informatics.
  doc_url: http://bobleesj.github.io/bobleesj.utils/
  dev_url: https://github.com/bobleesj/bobleesj.utils/

extra:
  recipe-maintainers:
    - bobleesj
